# docker-compose.yml

services:
  # rename "db" --> "pgdb" or something else
  pgdb:
    build:
      context: .
      dockerfile: docker/postgres/Dockerfile
    container_name: pgdb_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: b2b_semantic
    ports:
      - "5432:5432"
    volumes:
      - pg_data_new:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: b2b_semantic_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  pg_data_new:
